//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class YCXUAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YCXUAT()
        {
            this.CTYCXes = new HashSet<CTYCX>();
        }
    
        public int ID { get; set; }
        public System.DateTime NGAY { get; set; }
        public int IDNV { get; set; }
        public int IDCH { get; set; }
        public bool TINHTRANG { get; set; }
        public string GHICHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTYCX> CTYCXes { get; set; }
        public virtual CUAHANG CUAHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
